version: '3'

services:
  opencv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencv
    volumes:
      - ../python:/home/src/app
    stdin_open: true
    ports:
      - 3000:3000